// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZVf1Uk38Li3T3_GRWy-D5ACToVCFrRZc',
    appId: '1:516857737109:web:eea307d4bef6e65183909c',
    messagingSenderId: '516857737109',
    projectId: 'flutter-notification-app-7dc44',
    authDomain: 'flutter-notification-app-7dc44.firebaseapp.com',
    storageBucket: 'flutter-notification-app-7dc44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx0Eedc2Hi9U4NKiwcS4gJ5G81mRAkuNk',
    appId: '1:516857737109:android:3d2ead523c676bb783909c',
    messagingSenderId: '516857737109',
    projectId: 'flutter-notification-app-7dc44',
    storageBucket: 'flutter-notification-app-7dc44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJl2kLcWLd929JY1I3SPcKxxu-aUOrY1s',
    appId: '1:516857737109:ios:4941609345bf679983909c',
    messagingSenderId: '516857737109',
    projectId: 'flutter-notification-app-7dc44',
    storageBucket: 'flutter-notification-app-7dc44.firebasestorage.app',
    iosBundleId: 'com.example.notificationDemo',
  );
}
